project_id = "nvjbstcifphohmveiexf"

[functions.create-initial-situation-report]
verify_jwt = false

[functions.generate-situation-report]
verify_jwt = true

[functions.extract-text-report]
verify_jwt = false

[functions.transcribe-field-report]
verify_jwt = false

[functions.process-field-report-signals]
verify_jwt = false

[functions.fetch-tweets]
verify_jwt = false

[functions.evaluate-need]
verify_jwt = false
