project_id = "nvjbstcifphohmveiexf"

[functions.generate-situation-report]
verify_jwt = true

[functions.extract-text-report]
verify_jwt = false

[functions.transcribe-field-report]
verify_jwt = false
